main_url = 'https://www.google.com/'

stage_two_link = ('https://www.google.com/search?q=Совкомбанк&sca_esv=584537772&sxsrf'
                  '=AM9HkKmQW20n0YmigVGuQJapXb_TIrznYw%3A1700647225033&source=hp&ei=ONFdZbb3PKK0wPAPisCyyA4&iflsig'
                  '=AO6bgOgAAAAAZV3fSd3MEMDL8LNWolngUX4Acf3JW173&ved=0ahUKEwi28-_NrNeCAxUiGhAIHQqgDOkQ4dUDCAo&uact=5'
                  '&oq=Совкомбанк&gs_lp=Egdnd3Mtd2l6GgIYAyIU0KHQvtCy0LrQvtC80LHQsNC90LoyERAuGIAEGLEDGIMBGMcBGNEDMgUQABiABDILEAAYgAQYsQMYiwMyCxAAGIAEGLEDGIsDMg4QABiABBixAxiDARiLAzIOEAAYgAQYsQMYgwEYiwMyDhAAGIAEGLEDGIMBGIsDMg4QABiABBixAxiDARiLAzIOEAAYgAQYsQMYgwEYiwMyCxAAGIAEGLEDGIsDSPXFrwdQAFjmGHADeACQAQCYAVigAc8HqgECMTK4AQPIAQD4AQGoAgrCAg4QABiABBiKBRixAxiDAcICCxAAGIAEGLEDGIMBwgILEC4YgAQYsQMYgwHCAgsQLhiABBjHARivAcICBRAuGIAEwgIJEAAYARiABBgKwgIIEC4YgAQY1ALCAg0QLhjHARivARjqAhgnwgIHECMY6gIYJ8ICBBAjGCfCAgoQIxiABBiKBRgnwgIIEAAYgAQYsQM&sclient=gws-wiz#ip=1')

